kaijo
takutakutaku/ichiyasaGitSample pull request #1
Opened 2019-04-13 17:31 UTC by takutakutaku

kaijo

2019-04-14 15:05 UTC, takuhara commented
test

2019-04-14 15:10 UTC, ghost requested changes
見て

2019-04-14 15:10 UTC, takuhara commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ありがとう

2019-04-14 15:13 UTC, takutakutaku commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
プッシュ下で

2019-04-14 15:13 UTC, takuhara commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ありがとう

2019-04-14 15:14 UTC, ghost approved these changes

2019-04-14 15:18 UTC, merged

2019-07-19 06:14 UTC, takuhara commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
パブリック DNS (IPv4)
ec2-18-188-95-121.us-east-2.compute.amazonaws.com
18.188.95.121


2要素認証のバックアップコード
559974
426851
476222
893610
422689
491964
983176
611925
272728
911342

■ubuntu16.04インストール
quiet splash ---
を消して
nvme_load=yes
nouveau.modeset=0
を追加する。

deleteをずっと長押しでbios

2019-07-19 06:16 UTC, takuhara commented
パブリック DNS (IPv4)
ec2-18-188-95-121.us-east-2.compute.amazonaws.com
18.188.95.121


2要素認証のバックアップコード
559974
426851
476222
893610
422689
491964
983176
611925
272728
911342

■ubuntu16.04インストール
quiet splash ---
を消して
nvme_load=yes
nouveau.modeset=0
を追加する。

deleteをずっと長押しでbios